In [1]:
import csv
import numpy as np
from collections import defaultdict, Counter

In [3]:
count_dict = {} 
count_dict = defaultdict(lambda:0,count_dict)

winning_point = 10
candidate_point = 3

with open('lotto.csv', 'r', encoding='utf-8') as f:
    numbers_list = csv.reader(f)
    for numbers in numbers_list:
        for idx in range(6):
            winning_number = numbers[idx]
            count_dict[winning_number] += winning_point
        
        candidate_number = numbers[6]
        count_dict[candidate_number] += candidate_point

count_list = list(count_dict.items())
count_list.sort(key = lambda elem: int(elem[1]) * -1)

high_num_idx = int(np.linspace(1, len(count_list), 4)[1])

for _ in range(60):
    first_numbers = np.random.choice([int(i[0]) for i in count_list[:high_num_idx]], size=2, replace=False)
    second_numbers = np.random.choice([int(i[0]) for i in count_list[high_num_idx:]], size=4, replace=False)
    total_numbers = np.append(first_numbers, second_numbers) 
    print(np.sort(total_numbers))


[ 9 14 22 24 43 44]
[ 4 22 25 34 39 44]
[12 16 31 32 34 35]
[ 2  5  7 12 27 42]
[ 4 14 22 25 27 30]
[ 7  9 10 27 29 31]
[ 2  4  8 21 27 43]
[ 6 11 15 17 22 35]
[13 18 19 24 28 38]
[ 1  3  6  9 33 41]
[ 4 16 17 34 35 38]
[ 3  8  9 12 13 28]
[ 1  8 18 21 38 43]
[ 6  9 20 26 27 36]
[ 1  4 13 16 26 37]
[ 5 12 25 28 38 39]
[17 35 37 38 40 45]
[ 7  9 14 22 34 42]
[ 2  7 12 32 40 44]
[ 4 17 20 24 29 42]
[14 18 25 36 38 39]
[ 4  6 10 26 39 41]
[ 1  2  9 12 22 38]
[ 5 14 18 32 37 43]
[ 7 14 16 17 36 42]
[ 9 14 18 28 34 38]
[ 4  5 24 27 36 40]
[10 15 17 22 24 31]
[ 3 11 17 25 41 45]
[ 6 13 17 18 29 35]
[ 5 16 20 34 41 45]
[ 7 10 20 31 36 37]
[ 3  8 19 23 40 41]
[ 7 13 31 32 40 41]
[ 4 12 21 28 34 42]
[ 1  6  7 22 27 37]
[12 16 19 31 36 37]
[ 1  6  8 36 40 42]
[ 3 17 28 30 32 39]
[ 8 11 26 28 34 44]
[ 5  6 14 24 40 44]
[ 2  4 10 33 42 45]
[ 2  6  9 17 39 41]
[ 6 12 20 22 30 35]
[ 1 22 24 31 42 43]
[ 2  9 19 27 31 32]
[ 4 16 17 29 38 39]
[13 20 29 31 35 44]
[ 6  9 18 39 41 43]
[ 9 10 19 23 37 42]
