In [41]:
import csv
import numpy as np
from collections import defaultdict, Counter

In [157]:
count_dict = {} 
count_dict = defaultdict(lambda:0,count_dict)

winning_point = 10
candidate_point = 3

with open('lotto.csv', 'r', encoding='utf-8') as f:
    numbers_list = csv.reader(f)
    for numbers in numbers_list:
        for idx in range(6):
            winning_number = numbers[idx]
            count_dict[winning_number] += winning_point
        
        candidate_number = numbers[6]
        count_dict[candidate_number] += candidate_point

count_list = list(count_dict.items())
count_list.sort(key = lambda elem: int(elem[1]) * -1)

high_num_idx = int(np.linspace(1, len(count_list), 4)[1])

for _ in range(30):
    first_numbers = np.random.choice([int(i[0]) for i in count_list[:high_num_idx]], size=2, replace=False)
    second_numbers = np.random.choice([int(i[0]) for i in count_list[high_num_idx:]], size=4, replace=False)
    total_numbers = np.append(first_numbers, second_numbers) 
    print(np.sort(total_numbers))


[12 15 22 24 34 37]
[10 14 16 29 30 45]
[13 16 18 29 36 41]
[13 15 19 20 24 30]
[ 2  9 10 35 40 41]
[ 4 14 24 30 34 42]
[12 19 30 34 36 37]
[ 6 19 26 31 33 43]
[ 4  7 18 20 22 28]
[ 2 13 22 30 40 41]
[19 21 25 29 34 39]
[ 6 16 22 30 33 34]
[21 29 31 33 34 37]
[ 7 12 16 26 27 38]
[11 25 30 31 39 44]
[ 7 10 16 17 38 44]
[ 4 17 18 29 31 44]
[16 17 19 22 28 43]
[12 14 22 23 29 44]
[ 4  7 10 11 21 36]
[12 15 18 30 35 44]
[ 4 17 18 24 37 42]
[ 5 12 17 19 28 41]
[13 15 18 23 30 36]
[ 6 13 19 33 38 44]
[16 25 27 28 40 42]
[19 20 21 26 41 43]
[ 1 21 24 26 27 29]
[16 17 21 29 30 39]
[ 1 18 25 30 31 44]
